print("Hello world!")
print(3*"\n")
print(" hello Manish!")
print("hello to" , end=' ')
print("Everyone",end='!')
print("hi")
print("hello")
print("punam",end=".")
print("ahirrao",end="@")
print("gmail",end=".")
print("com")